CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_ZEPHYR_NUS=y

# Enable Console & Logging
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
# Disable other log backends like RTT to avoid duplicate prints
CONFIG_LOG_BACKEND_RTT=n
CONFIG_USE_SEGGER_RTT=n
# Disable low-level console getline
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETLINE=y
# Enable Zephyr Shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y


# Configure USB CDC ACM for Thingy:53 console
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_MULTIPLE_INSTANCES=y
CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="Thingy:53 Nordic UART Service sample"
CONFIG_CDC_ACM_SERIAL_PID=0x530E
CONFIG_USBD_CDC_ACM_LOG_LEVEL_OFF=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_ASYNC_ADAPTER=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_NRFX=n
CONFIG_BOOTLOADER_MCUBOOT=y

# Enable Debugging Support
CONFIG_DEBUG=y
# CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_OPTIMIZATIONS=y

#
CONFIG_GPIO=y
CONFIG_BT_DEVICE_NAME="sanc_thingy53"
CONFIG_ADC=y
CONFIG_PWM=y
CONFIG_SPI=y
CONFIG_BT_ATT_PREPARE_COUNT=5

# -------------------------------------------------------------
# Bluetooth MTU & Buffer Configuration
# -------------------------------------------------------------

# Set the maximum L2CAP TX MTU
CONFIG_BT_L2CAP_TX_MTU=247

# Set the RX/TX ACL buffer size to match MTU + L2CAP header (4 bytes)
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251

# Enable Link Layer Data Length Extension (DLE) to fit MTU in a single packet
CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251

# Enable floating point formatting in printf, printk, and LOG_* macros
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_PICOLIBC_IO_FLOAT=y

# sanc_thingy5340 cpuapp configuration
CONFIG_SHELL_PROMPT_UART="sanc:~$ "

# Sensor Subsystem Configuration
CONFIG_SENSOR=y

# ADXL362 driver
CONFIG_ADXL362=y
CONFIG_ADXL362_TRIGGER_GLOBAL_THREAD=y

# BH1749 color sensor
CONFIG_BH1749=y

# BME688 environmental sensor
CONFIG_BME680=y

# BMI270 IMU sensor
CONFIG_BMI270=y
CONFIG_BMI270_TRIGGER_GLOBAL_THREAD=y

# BMM150 magnetometer sensor
CONFIG_BMM150=y
CONFIG_BMM150_TRIGGER_GLOBAL_THREAD=y

# Regulator support
CONFIG_REGULATOR=y
CONFIG_REGULATOR_FIXED=y

# BLE OTA
# Enable MCUmgr and SMP BLE transport
CONFIG_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_TRANSPORT_BT_PERM_RW=y
CONFIG_MCUMGR_TRANSPORT_BT_REASSEMBLY=y
CONFIG_MCUMGR_TRANSPORT_BT_CONN_PARAM_CONTROL=y


# Enable MCUmgr groups for OS and Image management
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_GRP_IMG_VERBOSE_ERR=y

# Dependencies for MCUmgr & Image Manager
CONFIG_ZCBOR=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_FLASH_SIMULATOR=y
CONFIG_FLASH_SIMULATOR_DOUBLE_WRITES=y


# Recommended: Enable storage and flash boundaries
CONFIG_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_IMG_ERASE_PROGRESSIVELY=y

CONFIG_REBOOT=y

# Enable compiler size optimizations
CONFIG_SIZE_OPTIMIZATIONS=y

# Use compact nano printf
CONFIG_CBPRINTF_NANO=y

# Disable verbose logging in release build
# Use deferred logging (thread-safe for BLE)
CONFIG_LOG_MODE_DEFERRED=y