CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_ZEPHYR_NUS=y

# Enable Console & Logging
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
# Disable low-level console getline
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETLINE=y
# Enable Zephyr Shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y


# Configure USB CDC ACM for Thingy:53 console
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_MULTIPLE_INSTANCES=y
CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="Thingy:53 Nordic UART Service sample"
CONFIG_CDC_ACM_SERIAL_PID=0x530E
CONFIG_USBD_CDC_ACM_LOG_LEVEL_OFF=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_ASYNC_ADAPTER=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_NRFX=n
CONFIG_BOOTLOADER_MCUBOOT=y

# Enable Debugging Support
CONFIG_DEBUG=y
# CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_OPTIMIZATIONS=y

#
CONFIG_GPIO=y
CONFIG_BT_DEVICE_NAME="sanc_thingy53"
CONFIG_ADC=y
CONFIG_PWM=y
CONFIG_SPI=y

# Enable floating point formatting in printf, printk, and LOG_* macros
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_PICOLIBC_IO_FLOAT=y

# sanc_thingy5340 cpuapp configuration
CONFIG_SHELL_PROMPT_UART="sanc:~$ "

# Sensor Subsystem Configuration
CONFIG_SENSOR=y

# ADXL362 driver
CONFIG_ADXL362=y
CONFIG_ADXL362_TRIGGER_GLOBAL_THREAD=y

# BH1749 color sensor
CONFIG_BH1749=y

# BME688 environmental sensor
CONFIG_BME680=y

# BMI270 IMU sensor
CONFIG_BMI270=y

# BMM150 magnetometer sensor
CONFIG_BMM150=y

# Regulator support
CONFIG_REGULATOR=y
CONFIG_REGULATOR_FIXED=y
